services:
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./configs/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
    ports:
      - 1514:1514/udp
    command: --config.file=/etc/promtail/promtail-config.yml

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./configs/grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    ports:
      - 3001:3000

  loki:
    image: grafana/loki:latest
    volumes:
      - ./configs/loki:/etc/loki:ro
    command: --config.file=/etc/loki/loki-config.yml